import { Interpreter } from './interpreter'
import { ParseGiflang } from './parser'

const interpreter = new Interpreter((str) => console.log(str))
const root = ParseGiflang(`
CLASS; C; LCURLY;
  FUNCTION; _;_;B;O;O;L;_;_; LPAR; S; RPAR; LCURLY;
    RETURN; FALSE; SEMICOLON;
  RCURLY;

  FUNCTION; _;_;C;A;L;L;_;_; LPAR; S; RPAR; LCURLY;
    P;R;I;N;T; LPAR; QUOTE; X; QUOTE; RPAR; SEMICOLON;
  RCURLY;

  FUNCTION; A; LPAR; S; RPAR; LCURLY;
    P;R;I;N;T; LPAR; S; PROP; Z; RPAR; SEMICOLON;
  RCURLY;
RCURLY;

CLASS; D; LPAR; C; RPAR; LCURLY;
  FUNCTION; _;_;I;N;I;T;_;_; LPAR; S; COMMA; I; RPAR; LCURLY;
    S; PROP; Z; ASSIGN; I; SEMICOLON;
  RCURLY;

  FUNCTION; _;_;C;A;L;L;_;_; LPAR; S; RPAR; LCURLY;
    P;R;I;N;T; LPAR; S; PROP; C;E;C;K;Y; MUL; S;
      PROP; C;E;C;K;Y; RPAR; SEMICOLON;
  RCURLY;
  FUNCTION; F; LPAR; S; RPAR; LCURLY;
    P;R;I;N;T; LPAR; S; PROP; C;E;C;K;Y; PLUS; 1; RPAR; SEMICOLON;
  RCURLY;
RCURLY;

D; PROP; A; LPAR; D; LPAR; 5; RPAR; RPAR; SEMICOLON;
X; ASSIGN; LBRA; LBRA; QUOTE; K;O;K; QUOTE; RBRA; COMMA; QUOTE; C;E;C;K;Y; QUOTE; RBRA; SEMICOLON;
P;R;I;N;T; LPAR; X; RPAR; SEMICOLON;
X; LBRA; 0; RBRA; ASSIGN; 1;0;0; SEMICOLON;
P;R;I;N;T; LPAR; X; LBRA; 0; RBRA; RPAR; SEMICOLON;
`,
)
interpreter.visitProgramStmt(root)

const parkPlatz = `
CLASS; C; LCURLY;
  FUNCTION; _;_;C;A;L;L;_;_; LPAR; S; RPAR; LCURLY;
    P;R;I;N;T; LPAR; QUOTE; X; QUOTE; RPAR; SEMICOLON;
  RCURLY;

  FUNCTION; A; LPAR; S; RPAR; LCURLY;
    S; PROP; C;E;C;K;Y; ASSIGN; 3; SEMICOLON;
  RCURLY;
  FUNCTION; F; LPAR; S; RPAR; LCURLY;
    P;R;I;N;T; LPAR; S; PROP; C;E;C;K;Y; RPAR; SEMICOLON;
  RCURLY;
RCURLY;

CLASS; D; LPAR; C; RPAR; LCURLY;
  FUNCTION; _;_;C;A;L;L;_;_; LPAR; S; RPAR; LCURLY;
    P;R;I;N;T; LPAR; S; PROP; C;E;C;K;Y; MUL; S; 
      PROP; C;E;C;K;Y; RPAR; SEMICOLON;
  RCURLY;
  FUNCTION; F; LPAR; S; RPAR; LCURLY;
    P;R;I;N;T; LPAR; S; PROP; C;E;C;K;Y; PLUS; 1; RPAR; SEMICOLON;
  RCURLY;
RCURLY;

P; ASSIGN; D; LPAR; RPAR; SEMICOLON;
D; PROP; A; PROP; _;_;C;A;L;L;_;_; PROP; _;_;C;A;L;L;_;_; LPAR; P; RPAR; SEMICOLON;
P; PROP; F; LPAR; RPAR; SEMICOLON;
P; LPAR; RPAR; SEMICOLON;
LPAR; C; LPAR; RPAR; RPAR; ASSIGN; 3; SEMICOLON;
LPAR; C; LPAR; RPAR; RPAR; LPAR; RPAR; SEMICOLON;
`
