import { Interpreter } from './interpreter'
import { ParseGiflang } from './parser'

const interpreter = new Interpreter((str) => console.log(str))
const root = ParseGiflang(`
X; ASSIGN; LBRA;
  LBRA; 1; COMMA; 2; COMMA; 3; RBRA; COMMA;
  LBRA; 4; COMMA; 5; COMMA; 6; RBRA; RBRA; SEMICOLON;

FOR; LPAR;
    I; ASSIGN; 0; SEMICOLON;
    I; LT; X; PROP; l;e;n;g;t;h; LPAR; RPAR; SEMICOLON;
    I; ASSIGN; I; PLUS; 1;
  RPAR; LCURLY;
  FOR; LPAR;
    J; ASSIGN; 0; SEMICOLON;
    J; LT; X; LBRA; I; RBRA; PROP; l;e;n;g;t;h; LPAR; RPAR; SEMICOLON;
    J; ASSIGN; J; PLUS; 1;
  RPAR; LCURLY;
    P;R;I;N;T; LPAR; X; LBRA; I; RBRA; LBRA; J; RBRA; RPAR; SEMICOLON;
  RCURLY;
RCURLY;

j; ASSIGN; QUOTE; a;c;h; QUOTE; SEMICOLON;
P;R;I;N;T; LPAR; j; LBRA; 3; RBRA; RPAR; SEMICOLON;
`,
)
interpreter.visitProgramStmt(root)

const parkPlatz = `
CLASS; C; LCURLY;
  FUNCTION; _;_;C;A;L;L;_;_; LPAR; S; RPAR; LCURLY;
    P;R;I;N;T; LPAR; QUOTE; X; QUOTE; RPAR; SEMICOLON;
  RCURLY;

  FUNCTION; A; LPAR; S; RPAR; LCURLY;
    S; PROP; C;E;C;K;Y; ASSIGN; 3; SEMICOLON;
  RCURLY;
  FUNCTION; F; LPAR; S; RPAR; LCURLY;
    P;R;I;N;T; LPAR; S; PROP; C;E;C;K;Y; RPAR; SEMICOLON;
  RCURLY;
RCURLY;

CLASS; D; LPAR; C; RPAR; LCURLY;
  FUNCTION; _;_;C;A;L;L;_;_; LPAR; S; RPAR; LCURLY;
    P;R;I;N;T; LPAR; S; PROP; C;E;C;K;Y; MUL; S; 
      PROP; C;E;C;K;Y; RPAR; SEMICOLON;
  RCURLY;
  FUNCTION; F; LPAR; S; RPAR; LCURLY;
    P;R;I;N;T; LPAR; S; PROP; C;E;C;K;Y; PLUS; 1; RPAR; SEMICOLON;
  RCURLY;
RCURLY;

P; ASSIGN; D; LPAR; RPAR; SEMICOLON;
D; PROP; A; PROP; _;_;C;A;L;L;_;_; PROP; _;_;C;A;L;L;_;_; LPAR; P; RPAR; SEMICOLON;
P; PROP; F; LPAR; RPAR; SEMICOLON;
P; LPAR; RPAR; SEMICOLON;
LPAR; C; LPAR; RPAR; RPAR; ASSIGN; 3; SEMICOLON;
LPAR; C; LPAR; RPAR; RPAR; LPAR; RPAR; SEMICOLON;
`
